// Generate boundary-enforcement config for an existing linter.
//
// We deliberately do NOT implement import resolution. dependency-cruiser and
// import-linter already handle re-exports, barrel files, dynamic imports, path
// aliases and namespace packages — which is exactly where a hand-rolled checker
// dies. containers.yaml stays the source of truth; these files are generated
// artifacts and should be committed but never hand-edited.

import { basename } from 'node:path';

const rx = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const alt = (paths) => `^(${paths.map(rx).join('|')})/`;

export const TARGETS = {
  'dependency-cruiser': { file: '.dependency-cruiser.generated.cjs', languages: ['typescript', 'javascript'] },
  'import-linter': { file: '.importlinter.generated', languages: ['python'] },
};

export function targetForLanguage(language) {
  const found = Object.entries(TARGETS).find(([, t]) => t.languages.includes(language));
  return found ? found[0] : null;
}

// ---------------------------------------------------------------------------

function emitDependencyCruiser(model) {
  const { containers, policy } = model;
  const rules = [];

  for (const c of containers) {
    const allowed = model.allowed(c.id);
    const allowedIds = new Set(allowed.map((a) => a.id));
    const forbiddenTargets = containers.filter((o) => o.id !== c.id && !allowedIds.has(o.id));

    if (forbiddenTargets.length) {
      rules.push({
        name: `boundary-${c.id.replace(/\//g, '-')}`,
        severity: 'error',
        comment:
          `${c.id} may only consume: ${allowed.length ? [...allowedIds].join(', ') : '(nothing)'}. ` +
          `Adding an edge is a structural decision — update .wiki/containers.yaml and regenerate, ` +
          `do not work around this in code.`,
        from: { path: `^${rx(c.path)}/` },
        to: { path: alt(forbiddenTargets.map((o) => o.path)) },
      });
    }

    // Purity rules bind sub-paths INSIDE a container, so they are stricter than
    // the container's own edges: `orchestration/auth` may call `engine/token`,
    // but `orchestration/auth/domain` may not.
    for (const pure of policy.pure_paths) {
      const dir = `${c.path}/${pure}`;
      rules.push({
        name: `pure-${c.id.replace(/\//g, '-')}-${pure.replace(/\//g, '-')}`,
        severity: 'error',
        comment:
          `${c.id}/${pure} must not import anything outside itself — not even from its own ` +
          `container. Rules that need I/O belong one level up; if a rule needs data, take it ` +
          `as an argument.`,
        from: { path: `^${rx(dir)}/` },
        to: { path: `^${rx(policy.root)}/`, pathNot: `^${rx(dir)}/` },
      });
    }

    if (allowed.length) {
      rules.push({
        name: `surface-${c.id.replace(/\//g, '-')}`,
        severity: 'error',
        comment:
          `${c.id} must import its dependencies through their public surface ` +
          `(${policy.public_surface.join(', ')}), not by reaching into their internals.`,
        from: { path: `^${rx(c.path)}/` },
        to: {
          path: alt(allowed.map((a) => a.path)),
          pathNot: `^(${allowed.flatMap((a) => a.surface).map(rx).join('|')})$`,
        },
      });
    }
  }

  const body = `// GENERATED by claude-architect from .wiki/containers.yaml — do not edit.
// Regenerate: node <plugin>/scripts/containers.mjs emit dependency-cruiser
module.exports = ${JSON.stringify({
    forbidden: rules,
    options: {
      doNotFollow: { path: 'node_modules' },
      // Catches `import type { UserRow } from '../engine/...'` as a real edge.
      // Without it, invariant 5 (owned types) is unenforceable — a type can
      // cross two layers while no function call does.
      tsPreCompilationDeps: true,
      // Extensionless imports do not resolve without this, and an unresolved
      // import matches no rule — i.e. the gate silently passes everything.
      enhancedResolveOptions: {
        extensions: ['.ts', '.tsx', '.d.ts', '.js', '.jsx', '.mjs', '.cjs', '.json'],
      },
      exclude: { path: '\\.(test|spec)\\.[jt]sx?$' },
    },
  }, null, 2)};
`;
  return { file: TARGETS['dependency-cruiser'].file, body, ruleCount: rules.length };
}

// ---------------------------------------------------------------------------

function emitImportLinter(model) {
  const { containers, layers, policy } = model;
  const pkg = basename(policy.root);
  const mod = (path) => path.split('/').join('.').replace(/^[^.]+\./, `${pkg}.`);

  const out = [
    '# GENERATED by claude-architect from .wiki/containers.yaml — do not edit.',
    '# Regenerate: node <plugin>/scripts/containers.mjs emit import-linter',
    '',
    '[importlinter]',
    `root_package = ${pkg}`,
    '',
    '[importlinter:contract:layer-direction]',
    'name = Layer dependency direction (top may import bottom, never the reverse)',
    'type = layers',
    'layers =',
    ...layers.map((l) => `    ${pkg}.${l.id}`),
    '',
  ];

  let contracts = 1;
  const notes = [];
  for (const c of containers) {
    const allowedIds = new Set(model.allowed(c.id).map((a) => a.id));
    const forbidden = containers.filter((o) => o.id !== c.id && !allowedIds.has(o.id));
    const slug = c.id.replace(/[^A-Za-z0-9]+/g, '-');

    if (forbidden.length) {
      contracts += 1;
      out.push(
        `[importlinter:contract:${slug}]`,
        `name = ${c.id} allowed edges`,
        'type = forbidden',
        'source_modules =',
        `    ${mod(c.path)}`,
        'forbidden_modules =',
        ...forbidden.map((o) => `    ${mod(o.path)}`),
        '',
      );
    }

    // Purity: the cross-container half only. import-linter's `forbidden`
    // contract takes an explicit module list, so "imports nothing outside
    // itself" is expressible against other containers but not against the rest
    // of its OWN container without relying on descendant-matching semantics we
    // have not verified. The dependency-cruiser emitter enforces both halves.
    for (const pure of policy.pure_paths) {
      const others = containers.filter((o) => o.id !== c.id);
      if (!others.length) continue;
      contracts += 1;
      notes.push(`${c.id}/${pure}`);
      out.push(
        `[importlinter:contract:${slug}-pure-${pure.replace(/[^A-Za-z0-9]+/g, '-')}]`,
        `name = ${c.id}/${pure} is pure (no cross-container imports)`,
        'type = forbidden',
        'source_modules =',
        `    ${mod(`${c.path}/${pure}`)}`,
        'forbidden_modules =',
        ...others.map((o) => `    ${mod(o.path)}`),
        '',
      );
    }
  }

  if (notes.length) {
    out.splice(2, 0,
      '# NOTE: pure_paths contracts below cover CROSS-CONTAINER imports only.',
      '# The "no imports from the rest of its own container" half is enforced by the',
      '# dependency-cruiser emitter but not here — see docs/procedures/containers.md.',
    );
  }

  return { file: TARGETS['import-linter'].file, body: out.join('\n'), ruleCount: contracts };
}

// ---------------------------------------------------------------------------

export function emit(model, target) {
  switch (target) {
    case 'dependency-cruiser': return emitDependencyCruiser(model);
    case 'import-linter': return emitImportLinter(model);
    default:
      throw new Error(`unknown emit target \`${target}\` — expected one of ${Object.keys(TARGETS).join(', ')}`);
  }
}
